### PR TITLE
Adding CPU governors Lulzactive and Smartassv2

### PR DESCRIPTION
**Pull request by AreYouLoco**
Just merge for lulzactive and smartass2 support

### CODE REVIEW

**Comment by leskal** [comment]
before merge, have you test it? If yes, does the build completes? And what is the difference with these in cpu powersaving?

**Comment by AreYouLoco** [comment]
I dont really know which config file should I use to cross compile flexy kernel.

So if you point the config that was used before I would love to build it myself and test.

**Comment by leskal** [comment]
p9000_cyanogemod13_defconfig or p9000_flexy_defconfig

**Comment by AreYouLoco** [comment]
and which cross compiler should I use? I am debian user

**Comment by leskal** [comment]
https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip

**Comment by JonnyVR1** [comment]
There are merge conflicts in the first commit, please fix them

**Comment by JonnyVR1** [comment]
Pull request has been reverted, @AreYouLoco please fix the merge conflicts in your committed code.

**Pull request merged**
